name: mob_lab_manger
description: "A Flutter application for managing mobile lab operations."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  go_router: ^15.1.2
  flutter_native_splash: ^2.4.6
  connectivity_plus: ^6.1.4
  internet_connection_checker: ^3.0.1
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  background_image: assets/splash/light_mode_wave_bg.png
  image: assets/splash/mobile_repair_icon.png
  fullscreen: true

  color_dark: "#121212"
  background_image_dark: assets/splash/light_mode_wave_bg.png
  image_dark: assets/splash/mobile_repair_icon.png

  android_12:
    image: assets/splash/mobile_repair_icon_native_android12.png
    icon_background_color: "#FFFFFF"
    background_image: assets/splash/light_mode_wave_bg.png
    background_image_dark: assets/splash/light_mode_wave_bg.png

flutter:
  uses-material-design: true

  assets:
    - assets/splash/light_mode_wave_bg.png
    - assets/splash/dark_mode_wave_bg.png 
    - assets/splash/mobile_repair_icon.png
    - assets/splash/mobile_repair_icon_native.png
    - assets/splash/mobile_repair_icon_native_android12.png
