// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJHpkUk5o-h42beAyQteioS-MYCqt5Iic',
    appId: '1:713285850804:web:290a846f45c4bcb7ede9e1',
    messagingSenderId: '713285850804',
    projectId: 'moblabmanger',
    authDomain: 'moblabmanger.firebaseapp.com',
    storageBucket: 'moblabmanger.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBU6GY-nRWoEIbnVd5r95PYsTpcgHxjuI',
    appId: '1:713285850804:android:19251c70652daedbede9e1',
    messagingSenderId: '713285850804',
    projectId: 'moblabmanger',
    storageBucket: 'moblabmanger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHZ3Xl4C-wRoWJMNTdAzrdfAnHGZkU0F8',
    appId: '1:713285850804:ios:637a1fe5af1fad42ede9e1',
    messagingSenderId: '713285850804',
    projectId: 'moblabmanger',
    storageBucket: 'moblabmanger.firebasestorage.app',
    iosBundleId: 'com.example.mobLabManger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHZ3Xl4C-wRoWJMNTdAzrdfAnHGZkU0F8',
    appId: '1:713285850804:ios:637a1fe5af1fad42ede9e1',
    messagingSenderId: '713285850804',
    projectId: 'moblabmanger',
    storageBucket: 'moblabmanger.firebasestorage.app',
    iosBundleId: 'com.example.mobLabManger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJHpkUk5o-h42beAyQteioS-MYCqt5Iic',
    appId: '1:713285850804:web:0a8a63b459dcb767ede9e1',
    messagingSenderId: '713285850804',
    projectId: 'moblabmanger',
    authDomain: 'moblabmanger.firebaseapp.com',
    storageBucket: 'moblabmanger.firebasestorage.app',
  );
}
